plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/so-simple-theme
locale: en-GB
title: "Biology Society Blog"
description: "Blog maintained by the Biology Society of Ashoka University."
baseurl: 
url: "https://biosoc.github.io"
logo: "/img/logo.png"
date_format: "%d-%m-%Y"
read_time: true
words_per_minute: 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google-analytics: "UA-70147403-4"
twitter:
  shortname: DeeprajPandey
liquid:
  error_mode: strict
paginate: 7
paginate_path: /page:num/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate