plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/so-simple-theme

# Site settings
locale: en-GB
title: "Biology Society Blog"
description: "Blog maintained by the Biology Society of Ashoka University."
baseurl: 
url: "https://biosoc.github.io"
logo: "/img/logo.png"
date_format: "%B %d, %Y"
read_time: true
words_per_minute: 200
google_fonts:
  - name: Ubuntu
    weights: "400,400i,700,700i"
  - name: "Crimson Text"
    weights: "400,400i,700"
google-analytics: "UA-70147403-4"
twitter:
  shortname: DeeprajPandey

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
feed:
  path: atom.xml


# Search
search_full_content: true

# Pagination
paginate: 7
paginate_path: /page:num/

# Taxonomoy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

exclude: ["Gemfile", "Gemfile.lock"]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Deepraj Pandey
  picture: /img/deepraj.jpg
  email: deepraj11pandey@gmail.com
  twitter: DeeprajPandey
  links:
    - title: Twitter
      url: https://twitter.com/DeeprajPandey
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/deeprajpandey
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/DeeprajPandey
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/biosoc
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
