plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/so-simple-theme
locale: en-GB
title: "Biology Society Blog"
description: "Blog maintained by the Biology Society of Ashoka University."
baseurl: 
url: "https://biosoc.github.io"
logo: "/img/logo.png"
date_format: "%d-%m-%Y"
read_time: true
words_per_minute: 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google-analytics: "UA-70147403-4"
twitter:
  shortname: DeeprajPandey
liquid:
  error_mode: strict
search_full_content: true
paginate: 7
paginate_path: /page:num/
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
feed:
  path: atom.xml

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

exlude: ["Gemfile", "Gemfile.lock"]

comments: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
